name: Dev Github Actions
on:
  push:
    branches:
      - 'githubActions'
      - 'newLabs'
  pull_request:
    branches:
      - 'githubActions'
      - 'newLabs'
  schedule:
      - cron: '0 6 * * *' #daily at 9.00am EEST. #EEST = UTC + 3

jobs:
  superuser_suit:
      runs-on: ubuntu-20.04
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm ci
#      - run: npm config set script-shell "C:\Program Files\Git\bin\bash.exe"
      - name: Run tests as test:chrome:headless:stage:superuser
        run: npm run test:chrome:headless:stage:superuser || npm run test:chrome:headless:stage:superuser
      - name: Generate allure-report
        if: always()
        run: npm run allure:generate
      - name: Publishing Allure artifact to Github Actions
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: allure-report-superuser
          path: allure-report
  superuser_posts_suit:
      runs-on: windows-2019
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm ci
      - run: npm config set script-shell "C:\Program Files\Git\bin\bash.exe"
      - name: Run tests as test:chrome:headless:synchronized:stage:superuser
        run: npm run test:chrome:headless:synchronized:stage:superuser || npm run test:chrome:headless:synchronized:stage:superuser
      - name: Run tests as test:chrome:headless:synchronized:stage:student
        run: npm run test:chrome:headless:synchronized:stage:student || npm run test:chrome:headless:synchronized:stage:student
      - name: Generate allure-report
        if: always()
        run: npm run allure:generate
      - name: Publishing Allure artifact to Github Actions
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: allure-report-superuser-posts
          path: allure-report